blank_issues_enabled: true
contact_links:
  - name: Discussions Sérénimot
    url: https://github.com/arnaud71/serenimot/discussions
    about: Pour les questions générales, les échanges ouverts ou les idées encore exploratoires.
